There lived a monkey in a fruit tree. It enjoyed it's life by eating fruits and playing in the tree.
He did not have any friends. One day he say a crocodile eating rabbits. He went to the crocodile and said here after don't eat other animals.
I will give you delecious fruits everyday... The crocodile agreed his words and both became friends...

From that day the monkey started to give fruits to the crocodile and the crocodile take the fruits and himself and his wife both share the fruits and eat..
Days passed... One day the crocodile's wife asked the crocodile to bring that monkey to their's home... The crocodile asked why for that she replied that if the fruits is itslef this much taste then how taste will be the monkey's heart...
The crocodile disagreed her words. But she compelled him and he then agreed to her words... Then the crocodile went to monkey' home and said to the monkey that his wife wanted to see him... 
The monkey agreed to the crocodile's words and sat on the back of crocodile then both went to the crocodile's home... In half the way the crocoldile said the truth... 
The monkey suddenly got fear. Then he calmed down and thought of an idea.. He said to the crocodile that hey sorry my heart is so wet so I kept it in the tree itself to dry it...
Oh my friend said the crocodile and both went to monkey's home after returning the monkey climb up the tree so fastly. Then the monkey said that hey foolish crocodile can any one remove their heart from their body.
then the crocodile went to his home sadly.